# Generated by Django 5.1.5 on 2025-02-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_auth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='memo_phrase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
