# Generated by Django 5.1.5 on 2025-03-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_memo_phrase'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
