# Generated by Django 5.1.5 on 2025-02-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='auto_start_interval',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
