# Generated by Django 5.1.5 on 2025-02-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_auto_start_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='contract_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
    ]
