# Generated by Django 5.1.5 on 2025-02-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_coin_contract_address_game_is_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
    ]
