# Generated by Django 5.1.5 on 2025-02-26 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_gamesession_is_processing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinBetLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_bet', models.DecimalField(decimal_places=8, max_digits=20)),
                ('coin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.coin')),
            ],
        ),
    ]
