# Generated by Django 5.1.5 on 2025-02-26 12:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_coinbetlimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinbetlimit',
            name='max_bet',
        ),
        migrations.AddField(
            model_name='coinbetlimit',
            name='allowed_bets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=8, max_digits=20), default=list, size=None),
        ),
    ]
