# Generated by Django 5.1.5 on 2025-03-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_remove_coinbetlimit_max_bet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='memo_phrase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='transaction_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
