# Generated by Django 5.1.5 on 2025-03-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_transactionhistory_memo_phrase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='memo_phrase',
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_id',
            field=models.CharField(default='28ab2fe7-c093-4635-9761-e75d4c569721', max_length=255, unique=True),
        ),
    ]
