# Generated by Django 5.1.5 on 2025-03-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_remove_transactionhistory_memo_phrase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_id',
            field=models.CharField(default='9f768119-66a5-45d1-bf8e-ff1126658e6c', max_length=255, unique=True),
        ),
    ]
