# Generated by Django 5.1.5 on 2025-03-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_transactionhistory_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_id',
            field=models.CharField(default='fa0e1968-793b-4097-8e78-24f8b88ed9ca', max_length=255, unique=True),
        ),
    ]
