# Generated by Django 5.1.5 on 2025-03-10 11:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_transactionhistory_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
