# Generated by Django 5.1.5 on 2025-03-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_alter_transactionhistory_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='trace_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
