# Generated by Django 5.1.5 on 2025-03-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_transactionhistory_trace_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='memo_phrase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
