# Generated by Django 5.1.5 on 2025-03-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
    ]
