# Generated by Django 5.1.5 on 2025-03-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_withdrawalrequest_is_suspicious'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminNotification',
        ),
    ]
