# Generated by Django 5.1.5 on 2025-04-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_delete_adminnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='type',
            field=models.CharField(choices=[('arrival', 'Arrival'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('referral', 'Реферальный доход')], max_length=20),
        ),
    ]
