# Generated by Django 5.1.5 on 2025-05-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_alter_transactionhistory_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='coin',
        ),
        migrations.AddField(
            model_name='game',
            name='supported_coins',
            field=models.ManyToManyField(related_name='games', to='games.coin'),
        ),
    ]
