# Generated by Django 5.1.5 on 2025-05-01 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_remove_game_coin_game_supported_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamesession',
            name='coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_game_sessions', to='games.coin'),
        ),
    ]
