# Generated by Django 5.1.5 on 2025-05-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_usergamesession_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text='Локальный файл QR-кода', null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='coin',
            name='qr_code_url',
            field=models.URLField(blank=True, help_text='Ссылка на изображение QR-кода', null=True),
        ),
    ]
