# Generated by Django 5.1.5 on 2025-05-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_coin_qr_code_image_coin_qr_code_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={'verbose_name': 'Монета', 'verbose_name_plural': 'Монеты'},
        ),
        migrations.AlterModelOptions(
            name='coinbetlimit',
            options={'verbose_name': 'Установить лимит на монеты', 'verbose_name_plural': 'Установить лимит на монеты'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Игры', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='gamesession',
            options={'verbose_name': 'Игровые сессии', 'verbose_name_plural': 'Игровые сессии'},
        ),
        migrations.AlterModelOptions(
            name='gamesessionwinningcell',
            options={'verbose_name': 'Выигрышные ячейки', 'verbose_name_plural': 'Выигрышные ячейки'},
        ),
        migrations.AlterModelOptions(
            name='transactionhistory',
            options={'verbose_name': 'Иcтория тразакций', 'verbose_name_plural': 'Иcтория тразакций'},
        ),
        migrations.AlterModelOptions(
            name='userbalance',
            options={'verbose_name': 'Баланс пользователя', 'verbose_name_plural': 'Баланс пользователя'},
        ),
        migrations.AlterModelOptions(
            name='usergamesession',
            options={'verbose_name': 'Игровые сессии игроков', 'verbose_name_plural': 'Игровые сессии игроков'},
        ),
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'verbose_name': 'Заявка на вывод', 'verbose_name_plural': 'Заявка на вывод'},
        ),
    ]
